import type { RawBusinessRecord } from "./types";
import { KNOWN_TOWNS } from "@/lib/geo";

// Jitter a town's coordinates slightly so businesses in the same town aren't
// stacked on exactly the same point.
function jitter(lat: number, lng: number, seed: number): { latitude: number; longitude: number } {
  const dLat = (((seed * 37) % 100) / 100 - 0.5) * 0.03;
  const dLng = (((seed * 53) % 100) / 100 - 0.5) * 0.03;
  return { latitude: Number((lat + dLat).toFixed(5)), longitude: Number((lng + dLng).toFixed(5)) };
}

function town(name: string) {
  const t = KNOWN_TOWNS.find((k) => k.name === name);
  if (!t) throw new Error(`Unknown town in mock data: ${name}`);
  return t;
}

// 34 realistic UK local service businesses spread across categories and
// towns, with deliberately varied website/social/review profiles so search
// filters (keyword, location, radius, min reviews, max results) all have
// something meaningful to bite into.
export const MOCK_BUSINESSES: RawBusinessRecord[] = [
  {
    id: "b001",
    business_name: "Solent Roofing Specialists",
    category: "roofers",
    address: "14 Fratton Road",
    town_city: "Portsmouth",
    postcode: "PO1 5BX",
    phone: "023 9282 1144",
    website_url: null,
    google_maps_url: "https://maps.google.com/?cid=1001",
    google_rating: 4.9,
    google_review_count: 187,
    ...jitter(town("Portsmouth").lat, town("Portsmouth").lng, 1),
    email: null,
    facebook_url: "https://facebook.com/solentroofingspecialists",
    instagram_url: null,
    linkedin_url: null,
  },
  {
    id: "b002",
    business_name: "Hampshire Roof Repairs",
    category: "roofers",
    address: "22 London Road",
    town_city: "Portsmouth",
    postcode: "PO2 9DE",
    phone: "023 9265 3390",
    website_url: "https://www.hampshireroofrepairs.example.co.uk",
    google_maps_url: "https://maps.google.com/?cid=1002",
    google_rating: 4.6,
    google_review_count: 63,
    ...jitter(town("Portsmouth").lat, town("Portsmouth").lng, 2),
    email: "info@hampshireroofrepairs.example.co.uk",
    facebook_url: "https://facebook.com/hampshireroofrepairs",
    instagram_url: null,
    linkedin_url: null,
  },
  {
    id: "b003",
    business_name: "Southsea Roofing Co",
    category: "roofers",
    address: "8 Palmerston Road",
    town_city: "Portsmouth",
    postcode: "PO5 3QQ",
    phone: "023 9273 5521",
    website_url: "https://www.southsearoofing.example.com",
    google_maps_url: "https://maps.google.com/?cid=1003",
    google_rating: 4.2,
    google_review_count: 29,
    ...jitter(town("Portsmouth").lat, town("Portsmouth").lng, 3),
    email: "hello@southsearoofing.example.com",
    facebook_url: null,
    instagram_url: "https://instagram.com/southsearoofingco",
    linkedin_url: null,
  },
  {
    id: "b004",
    business_name: "Waterlooville Roofing Ltd",
    category: "roofers",
    address: "3 London Road",
    town_city: "Waterlooville",
    postcode: "PO7 7EX",
    phone: "023 9226 7712",
    website_url: null,
    google_maps_url: "https://maps.google.com/?cid=1004",
    google_rating: 4.8,
    google_review_count: 112,
    ...jitter(town("Waterlooville").lat, town("Waterlooville").lng, 4),
    email: null,
    facebook_url: null,
    instagram_url: null,
    linkedin_url: null,
  },
  {
    id: "b005",
    business_name: "Fareham Flat Roofing",
    category: "roofers",
    address: "56 West Street",
    town_city: "Fareham",
    postcode: "PO16 0JW",
    phone: "01329 822 156",
    website_url: "https://www.farehamflatroofing.example.co.uk",
    google_maps_url: "https://maps.google.com/?cid=1005",
    google_rating: 4.7,
    google_review_count: 54,
    ...jitter(town("Fareham").lat, town("Fareham").lng, 5),
    email: "quotes@farehamflatroofing.example.co.uk",
    facebook_url: "https://facebook.com/farehamflatroofing",
    instagram_url: null,
    linkedin_url: null,
  },
  {
    id: "b006",
    business_name: "Portsmouth Plumbing Pros",
    category: "plumbers",
    address: "101 Kingston Road",
    town_city: "Portsmouth",
    postcode: "PO2 7DZ",
    phone: "023 9266 4410",
    website_url: null,
    google_maps_url: "https://maps.google.com/?cid=1006",
    google_rating: 4.9,
    google_review_count: 204,
    ...jitter(town("Portsmouth").lat, town("Portsmouth").lng, 6),
    email: null,
    facebook_url: "https://facebook.com/portsmouthplumbingpros",
    instagram_url: "https://instagram.com/portsmouthplumbingpros",
    linkedin_url: null,
  },
  {
    id: "b007",
    business_name: "Rapid Response Plumbers PO",
    category: "plumbers",
    address: "9 Albert Road",
    town_city: "Portsmouth",
    postcode: "PO5 2SE",
    phone: "023 9229 8871",
    website_url: "https://www.rapidresponseplumbers.example.com",
    google_maps_url: "https://maps.google.com/?cid=1007",
    google_rating: 4.4,
    google_review_count: 41,
    ...jitter(town("Portsmouth").lat, town("Portsmouth").lng, 7),
    email: "office@rapidresponseplumbers.example.com",
    facebook_url: null,
    instagram_url: null,
    linkedin_url: null,
  },
  {
    id: "b008",
    business_name: "Havant Heating & Plumbing",
    category: "plumbers",
    address: "45 East Street",
    town_city: "Havant",
    postcode: "PO9 1AA",
    phone: "023 9247 1102",
    website_url: "https://www.havantheatingplumbing.example.co.uk",
    google_maps_url: "https://maps.google.com/?cid=1008",
    google_rating: 4.8,
    google_review_count: 96,
    ...jitter(town("Havant").lat, town("Havant").lng, 8),
    email: "info@havantheatingplumbing.example.co.uk",
    facebook_url: "https://facebook.com/havantheatingplumbing",
    instagram_url: null,
    linkedin_url: null,
  },
  {
    id: "b009",
    business_name: "Gosport Gas & Plumbing",
    category: "plumbers",
    address: "17 High Street",
    town_city: "Gosport",
    postcode: "PO12 1DA",
    phone: "023 9252 6634",
    website_url: null,
    google_maps_url: "https://maps.google.com/?cid=1009",
    google_rating: 3.9,
    google_review_count: 18,
    ...jitter(town("Gosport").lat, town("Gosport").lng, 9),
    email: null,
    facebook_url: null,
    instagram_url: null,
    linkedin_url: null,
  },
  {
    id: "b010",
    business_name: "Solent Landscaping & Design",
    category: "landscapers",
    address: "2 Locksway Road",
    town_city: "Portsmouth",
    postcode: "PO4 8LR",
    phone: "023 9273 1189",
    website_url: "https://www.solentlandscaping.example.com",
    google_maps_url: "https://maps.google.com/?cid=1010",
    google_rating: 4.9,
    google_review_count: 143,
    ...jitter(town("Portsmouth").lat, town("Portsmouth").lng, 10),
    email: "studio@solentlandscaping.example.com",
    facebook_url: "https://facebook.com/solentlandscaping",
    instagram_url: "https://instagram.com/solentlandscaping",
    linkedin_url: null,
  },
  {
    id: "b011",
    business_name: "Fareham Garden Makeovers",
    category: "landscapers",
    address: "70 Highlands Road",
    town_city: "Fareham",
    postcode: "PO15 6EG",
    phone: "01329 234 567",
    website_url: null,
    google_maps_url: "https://maps.google.com/?cid=1011",
    google_rating: 4.7,
    google_review_count: 71,
    ...jitter(town("Fareham").lat, town("Fareham").lng, 11),
    email: null,
    facebook_url: "https://facebook.com/farehamgardenmakeovers",
    instagram_url: null,
    linkedin_url: null,
  },
  {
    id: "b012",
    business_name: "Chichester Landscapes",
    category: "landscapers",
    address: "5 Southgate",
    town_city: "Chichester",
    postcode: "PO19 1DP",
    phone: "01243 771 220",
    website_url: "https://www.chichesterlandscapes.example.co.uk",
    google_maps_url: "https://maps.google.com/?cid=1012",
    google_rating: 4.3,
    google_review_count: 33,
    ...jitter(town("Chichester").lat, town("Chichester").lng, 12),
    email: "hello@chichesterlandscapes.example.co.uk",
    facebook_url: null,
    instagram_url: "https://instagram.com/chichesterlandscapes",
    linkedin_url: null,
  },
  {
    id: "b013",
    business_name: "Waterlooville Turf & Fencing",
    category: "landscapers",
    address: "12 Hambledon Road",
    town_city: "Waterlooville",
    postcode: "PO7 6DX",
    phone: "023 9225 4471",
    website_url: null,
    google_maps_url: "https://maps.google.com/?cid=1013",
    google_rating: 4.1,
    google_review_count: 22,
    ...jitter(town("Waterlooville").lat, town("Waterlooville").lng, 13),
    email: null,
    facebook_url: null,
    instagram_url: null,
    linkedin_url: null,
  },
  {
    id: "b014",
    business_name: "Portsmouth Electrical Services",
    category: "electricians",
    address: "88 Commercial Road",
    town_city: "Portsmouth",
    postcode: "PO1 1BP",
    phone: "023 9282 9910",
    website_url: "https://www.portsmouthelectrical.example.com",
    google_maps_url: "https://maps.google.com/?cid=1014",
    google_rating: 4.9,
    google_review_count: 168,
    ...jitter(town("Portsmouth").lat, town("Portsmouth").lng, 14),
    email: "bookings@portsmouthelectrical.example.com",
    facebook_url: "https://facebook.com/portsmouthelectrical",
    instagram_url: null,
    linkedin_url: null,
  },
  {
    id: "b015",
    business_name: "Southsea Sparks Electrical",
    category: "electricians",
    address: "31 Elm Grove",
    town_city: "Portsmouth",
    postcode: "PO5 1LR",
    phone: "023 9229 4456",
    website_url: null,
    google_maps_url: "https://maps.google.com/?cid=1015",
    google_rating: 4.6,
    google_review_count: 58,
    ...jitter(town("Portsmouth").lat, town("Portsmouth").lng, 15),
    email: null,
    facebook_url: "https://facebook.com/southseasparks",
    instagram_url: null,
    linkedin_url: null,
  },
  {
    id: "b016",
    business_name: "Havant Electrical Contractors",
    category: "electricians",
    address: "60 West Street",
    town_city: "Havant",
    postcode: "PO9 1LA",
    phone: "023 9248 8802",
    website_url: "https://www.havantelectrical.example.co.uk",
    google_maps_url: "https://maps.google.com/?cid=1016",
    google_rating: 3.8,
    google_review_count: 14,
    ...jitter(town("Havant").lat, town("Havant").lng, 16),
    email: "admin@havantelectrical.example.co.uk",
    facebook_url: null,
    instagram_url: null,
    linkedin_url: null,
  },
  {
    id: "b017",
    business_name: "Solent Builders Group",
    category: "builders",
    address: "40 Fratton Road",
    town_city: "Portsmouth",
    postcode: "PO1 5BS",
    phone: "023 9265 1177",
    website_url: "https://www.solentbuildersgroup.example.com",
    google_maps_url: "https://maps.google.com/?cid=1017",
    google_rating: 4.9,
    google_review_count: 231,
    ...jitter(town("Portsmouth").lat, town("Portsmouth").lng, 17),
    email: "enquiries@solentbuildersgroup.example.com",
    facebook_url: "https://facebook.com/solentbuildersgroup",
    instagram_url: "https://instagram.com/solentbuildersgroup",
    linkedin_url: null,
  },
  {
    id: "b018",
    business_name: "Fareham Building Contractors",
    category: "builders",
    address: "12 Trinity Street",
    town_city: "Fareham",
    postcode: "PO16 7TA",
    phone: "01329 456 112",
    website_url: null,
    google_maps_url: "https://maps.google.com/?cid=1018",
    google_rating: 4.5,
    google_review_count: 47,
    ...jitter(town("Fareham").lat, town("Fareham").lng, 18),
    email: null,
    facebook_url: "https://facebook.com/farehambuildingcontractors",
    instagram_url: null,
    linkedin_url: null,
  },
  {
    id: "b019",
    business_name: "Gosport General Builders",
    category: "builders",
    address: "3 Stoke Road",
    town_city: "Gosport",
    postcode: "PO12 1JB",
    phone: "023 9258 3321",
    website_url: "https://www.gosportgeneralbuilders.example.co.uk",
    google_maps_url: "https://maps.google.com/?cid=1019",
    google_rating: 4.0,
    google_review_count: 26,
    ...jitter(town("Gosport").lat, town("Gosport").lng, 19),
    email: "info@gosportgeneralbuilders.example.co.uk",
    facebook_url: null,
    instagram_url: null,
    linkedin_url: null,
  },
  {
    id: "b020",
    business_name: "Portsmouth Painters & Decorators",
    category: "painters and decorators",
    address: "19 Copnor Road",
    town_city: "Portsmouth",
    postcode: "PO3 5EF",
    phone: "023 9266 7734",
    website_url: null,
    google_maps_url: "https://maps.google.com/?cid=1020",
    google_rating: 4.8,
    google_review_count: 89,
    ...jitter(town("Portsmouth").lat, town("Portsmouth").lng, 20),
    email: null,
    facebook_url: "https://facebook.com/portsmouthpaintersdecorators",
    instagram_url: "https://instagram.com/portsmouthpaintersdecorators",
    linkedin_url: null,
  },
  {
    id: "b021",
    business_name: "Winchester Decor Co",
    category: "painters and decorators",
    address: "7 Jewry Street",
    town_city: "Winchester",
    postcode: "SO23 8RY",
    phone: "01962 234 771",
    website_url: "https://www.winchesterdecor.example.com",
    google_maps_url: "https://maps.google.com/?cid=1021",
    google_rating: 4.6,
    google_review_count: 52,
    ...jitter(town("Winchester").lat, town("Winchester").lng, 21),
    email: "studio@winchesterdecor.example.com",
    facebook_url: null,
    instagram_url: "https://instagram.com/winchesterdecor",
    linkedin_url: null,
  },
  {
    id: "b022",
    business_name: "Chichester Painting Services",
    category: "painters and decorators",
    address: "14 North Street",
    town_city: "Chichester",
    postcode: "PO19 1LQ",
    phone: "01243 556 890",
    website_url: null,
    google_maps_url: "https://maps.google.com/?cid=1022",
    google_rating: 3.7,
    google_review_count: 9,
    ...jitter(town("Chichester").lat, town("Chichester").lng, 22),
    email: null,
    facebook_url: null,
    instagram_url: null,
    linkedin_url: null,
  },
  {
    id: "b023",
    business_name: "Solent Driveways & Paving",
    category: "driveways and paving",
    address: "25 Milton Road",
    town_city: "Portsmouth",
    postcode: "PO3 6AR",
    phone: "023 9273 9981",
    website_url: "https://www.solentdriveways.example.co.uk",
    google_maps_url: "https://maps.google.com/?cid=1023",
    google_rating: 4.9,
    google_review_count: 156,
    ...jitter(town("Portsmouth").lat, town("Portsmouth").lng, 23),
    email: "quotes@solentdriveways.example.co.uk",
    facebook_url: "https://facebook.com/solentdriveways",
    instagram_url: null,
    linkedin_url: null,
  },
  {
    id: "b024",
    business_name: "Fareham Block Paving",
    category: "driveways and paving",
    address: "33 Highlands Road",
    town_city: "Fareham",
    postcode: "PO15 5RT",
    phone: "01329 887 213",
    website_url: null,
    google_maps_url: "https://maps.google.com/?cid=1024",
    google_rating: 4.4,
    google_review_count: 37,
    ...jitter(town("Fareham").lat, town("Fareham").lng, 24),
    email: null,
    facebook_url: "https://facebook.com/farehamblockpaving",
    instagram_url: null,
    linkedin_url: null,
  },
  {
    id: "b025",
    business_name: "Havant Driveway Specialists",
    category: "driveways and paving",
    address: "8 Elm Lane",
    town_city: "Havant",
    postcode: "PO9 2LL",
    phone: "023 9249 1123",
    website_url: "https://www.havantdriveways.example.com",
    google_maps_url: "https://maps.google.com/?cid=1025",
    google_rating: 4.1,
    google_review_count: 19,
    ...jitter(town("Havant").lat, town("Havant").lng, 25),
    email: "office@havantdriveways.example.com",
    facebook_url: null,
    instagram_url: null,
    linkedin_url: null,
  },
  {
    id: "b026",
    business_name: "Portsmouth Tree Surgeons",
    category: "tree surgeons",
    address: "51 Copnor Road",
    town_city: "Portsmouth",
    postcode: "PO3 5AH",
    phone: "023 9265 8823",
    website_url: null,
    google_maps_url: "https://maps.google.com/?cid=1026",
    google_rating: 4.9,
    google_review_count: 121,
    ...jitter(town("Portsmouth").lat, town("Portsmouth").lng, 26),
    email: null,
    facebook_url: "https://facebook.com/portsmouthtreesurgeons",
    instagram_url: "https://instagram.com/portsmouthtreesurgeons",
    linkedin_url: null,
  },
  {
    id: "b027",
    business_name: "Waterlooville Tree Care",
    category: "tree surgeons",
    address: "18 Hambledon Road",
    town_city: "Waterlooville",
    postcode: "PO7 6EY",
    phone: "023 9224 5567",
    website_url: "https://www.waterloovilletreecare.example.co.uk",
    google_maps_url: "https://maps.google.com/?cid=1027",
    google_rating: 4.7,
    google_review_count: 44,
    ...jitter(town("Waterlooville").lat, town("Waterlooville").lng, 27),
    email: "info@waterloovilletreecare.example.co.uk",
    facebook_url: null,
    instagram_url: null,
    linkedin_url: null,
  },
  {
    id: "b028",
    business_name: "Portsmouth Locksmiths 24/7",
    category: "locksmiths",
    address: "5 Kingston Crescent",
    town_city: "Portsmouth",
    postcode: "PO2 8AH",
    phone: "023 9266 1190",
    website_url: "https://www.portsmouthlocksmiths247.example.com",
    google_maps_url: "https://maps.google.com/?cid=1028",
    google_rating: 4.8,
    google_review_count: 203,
    ...jitter(town("Portsmouth").lat, town("Portsmouth").lng, 28),
    email: "help@portsmouthlocksmiths247.example.com",
    facebook_url: "https://facebook.com/portsmouthlocksmiths247",
    instagram_url: null,
    linkedin_url: null,
  },
  {
    id: "b029",
    business_name: "Gosport Lock & Key",
    category: "locksmiths",
    address: "22 Stoke Road",
    town_city: "Gosport",
    postcode: "PO12 1LZ",
    phone: "023 9252 9987",
    website_url: null,
    google_maps_url: "https://maps.google.com/?cid=1029",
    google_rating: 4.3,
    google_review_count: 27,
    ...jitter(town("Gosport").lat, town("Gosport").lng, 29),
    email: null,
    facebook_url: null,
    instagram_url: null,
    linkedin_url: null,
  },
  {
    id: "b030",
    business_name: "Solent Carpentry & Joinery",
    category: "carpenters",
    address: "60 Locksway Road",
    town_city: "Portsmouth",
    postcode: "PO4 8LS",
    phone: "023 9273 4487",
    website_url: "https://www.solentcarpentry.example.co.uk",
    google_maps_url: "https://maps.google.com/?cid=1030",
    google_rating: 4.9,
    google_review_count: 98,
    ...jitter(town("Portsmouth").lat, town("Portsmouth").lng, 30),
    email: "workshop@solentcarpentry.example.co.uk",
    facebook_url: "https://facebook.com/solentcarpentry",
    instagram_url: "https://instagram.com/solentcarpentry",
    linkedin_url: null,
  },
  {
    id: "b031",
    business_name: "Winchester Bespoke Joinery",
    category: "carpenters",
    address: "22 Jewry Street",
    town_city: "Winchester",
    postcode: "SO23 8RZ",
    phone: "01962 771 344",
    website_url: null,
    google_maps_url: "https://maps.google.com/?cid=1031",
    google_rating: 4.6,
    google_review_count: 34,
    ...jitter(town("Winchester").lat, town("Winchester").lng, 31),
    email: null,
    facebook_url: "https://facebook.com/winchesterbespokejoinery",
    instagram_url: null,
    linkedin_url: null,
  },
  {
    id: "b032",
    business_name: "Manchester Roofing Experts",
    category: "roofers",
    address: "120 Deansgate",
    town_city: "Manchester",
    postcode: "M3 2GB",
    phone: "0161 234 5678",
    website_url: "https://www.manchesterroofingexperts.example.com",
    google_maps_url: "https://maps.google.com/?cid=1032",
    google_rating: 4.7,
    google_review_count: 88,
    ...jitter(town("Manchester").lat, town("Manchester").lng, 32),
    email: "info@manchesterroofingexperts.example.com",
    facebook_url: "https://facebook.com/manchesterroofingexperts",
    instagram_url: null,
    linkedin_url: null,
  },
  {
    id: "b033",
    business_name: "Bristol Landscaping Studio",
    category: "landscapers",
    address: "9 Park Street",
    town_city: "Bristol",
    postcode: "BS1 5NB",
    phone: "0117 987 6543",
    website_url: null,
    google_maps_url: "https://maps.google.com/?cid=1033",
    google_rating: 4.9,
    google_review_count: 132,
    ...jitter(town("Bristol").lat, town("Bristol").lng, 33),
    email: null,
    facebook_url: "https://facebook.com/bristollandscapingstudio",
    instagram_url: "https://instagram.com/bristollandscapingstudio",
    linkedin_url: null,
  },
  {
    id: "b034",
    business_name: "Leeds Plumbing & Heating",
    category: "plumbers",
    address: "45 Briggate",
    town_city: "Leeds",
    postcode: "LS1 6HD",
    phone: "0113 246 8800",
    website_url: "https://www.leedsplumbingheating.example.co.uk",
    google_maps_url: "https://maps.google.com/?cid=1034",
    google_rating: 4.2,
    google_review_count: 21,
    ...jitter(town("Leeds").lat, town("Leeds").lng, 34),
    email: "office@leedsplumbingheating.example.co.uk",
    facebook_url: null,
    instagram_url: null,
    linkedin_url: null,
  },
];
